<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResourcesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('resources')->insert(
            [
                [
                    'slug'                  => 'Acacia',
                    'en'                    => 'Acacia',
                    'fr'                    => 'Acacia',
                    'ar'                    => 'سنط',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Aggregates',
                    'en'                    => 'Aggregates',
                    'fr'                    => 'Agrégats',
                    'ar'                    => 'تراكمات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Agroindustry',
                    'en'                    => 'Agroindustry',
                    'fr'                    => 'Agroindustrie',
                    'ar'                    => 'الصناعة الزراعية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Alumina',
                    'en'                    => 'Alumina',
                    'fr'                    => 'Alumine',
                    'ar'                    => 'أكسيد الألمنيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Aluminous Clay',
                    'en'                    => 'Aluminous Clay',
                    'fr'                    => 'Argile alumineuse',
                    'ar'                    => 'صلصال يحتوي على أكسيد الألمنيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Aluminum',
                    'en'                    => 'Aluminum',
                    'fr'                    => 'Aluminium',
                    'ar'                    => 'الألمنيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Amethyst',
                    'en'                    => 'Amethyst',
                    'fr'                    => 'Améthyste',
                    'ar'                    => 'جمشت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ammonium Sulfate',
                    'en'                    => 'Ammonium Sulfate',
                    'fr'                    => 'Sulfate d\'ammonium',
                    'ar'                    => 'كبريتات الأمونيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ananas comosus (Pineapple plant)',
                    'en'                    => 'Ananas comosus (Pineapple plant)',
                    'fr'                    => 'Ananas comosus (plante d\'ananas)',
                    'ar'                    => 'أناناس وبري',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Antimony',
                    'en'                    => 'Antimony',
                    'fr'                    => 'Antimoine',
                    'ar'                    => 'أنتيمون',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Arsenic',
                    'en'                    => 'Arsenic',
                    'fr'                    => 'Arsenic',
                    'ar'                    => 'زرنيخ',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Asbestos',
                    'en'                    => 'Asbestos',
                    'fr'                    => 'Amiante',
                    'ar'                    => 'الأسبستوس',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Attapulgite',
                    'en'                    => 'Attapulgite',
                    'fr'                    => 'Attapulgite',
                    'ar'                    => 'أتابولغايت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bananas',
                    'en'                    => 'Bananas',
                    'fr'                    => 'Bananes',
                    'ar'                    => 'موز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Barite',
                    'en'                    => 'Barite',
                    'fr'                    => 'Barytine',
                    'ar'                    => ' الباريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Base metals',
                    'en'                    => 'Base metals',
                    'fr'                    => 'Métaux de base',
                    'ar'                    => 'فلزات وضيعة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bauxite',
                    'en'                    => 'Bauxite',
                    'fr'                    => 'Bauxite',
                    'ar'                    => 'بوكسيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bauxite-Aluminum',
                    'en'                    => 'Bauxite-Aluminum',
                    'fr'                    => 'Bauxite-Aluminium',
                    'ar'                    => 'بوكسيت-ألمنيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bentonite',
                    'en'                    => 'Bentonite',
                    'fr'                    => 'Bentonite',
                    'ar'                    => 'بنتونيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Beryl',
                    'en'                    => 'Beryl',
                    'fr'                    => 'Béryl',
                    'ar'                    => 'بيريل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Beryllium',
                    'en'                    => 'Beryllium',
                    'fr'                    => 'Béryllium',
                    'ar'                    => 'بيريليوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Biofuels',
                    'en'                    => 'Biofuels',
                    'fr'                    => 'Biocarburants',
                    'ar'                    => 'وقود حيوي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bismuth',
                    'en'                    => 'Bismuth',
                    'fr'                    => 'Bismuth',
                    'ar'                    => 'بزموت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Bituminous coal',
                    'en'                    => 'Bituminous coal',
                    'fr'                    => 'Houille',
                    'ar'                    => 'الفحم القاري',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Borates',
                    'en'                    => 'Borates',
                    'fr'                    => 'Borate',
                    'ar'                    => 'بورات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Boron',
                    'en'                    => 'Boron',
                    'fr'                    => 'Bore',
                    'ar'                    => 'بورون',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Brown coal',
                    'en'                    => 'Brown coal',
                    'fr'                    => 'Charbon brun',
                    'ar'                    => 'فحم بني',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Cadmium',
                    'en'                    => 'Cadmium',
                    'fr'                    => 'Cadmium',
                    'ar'                    => 'كادميوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Caesium',
                    'en'                    => 'Caesium',
                    'fr'                    => 'Césium',
                    'ar'                    => 'سيزيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Calcium Carbonate',
                    'en'                    => 'Calcium Carbonate',
                    'fr'                    => 'Carbonate de calcium',
                    'ar'                    => 'كربونات الكالسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Calcrete',
                    'en'                    => 'Calcrete',
                    'fr'                    => 'Calcrète',
                    'ar'                    => 'كالسيت خرساني',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Castor oil (Ricinus communis)',
                    'en'                    => 'Castor oil (Ricinus communis)',
                    'fr'                    => 'Huile de ricin (Ricin commun)',
                    'ar'                    => 'زيت خروع',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Cereal crops',
                    'en'                    => 'Cereal crops',
                    'fr'                    => 'Cultures de céréales"',
                    'ar'                    => 'محاصيل الحبوب',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Cerium',
                    'en'                    => 'Cerium',
                    'fr'                    => 'Cérium',
                    'ar'                    => 'سيريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Chromite',
                    'en'                    => 'Chromite',
                    'fr'                    => 'Chromite',
                    'ar'                    => 'كروميت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Chromium',
                    'en'                    => 'Chromium',
                    'fr'                    => 'Chrome',
                    'ar'                    => 'كروم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Chrysoprase',
                    'en'                    => 'Chrysoprase',
                    'fr'                    => 'Chrysoprase',
                    'ar'                    => 'كريسوبريز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Citrus',
                    'en'                    => 'Citrus',
                    'fr'                    => 'Citrus',
                    'ar'                    => 'حمضيات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Clay',
                    'en'                    => 'Clay',
                    'fr'                    => 'Argile',
                    'ar'                    => 'صلصال',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Coal',
                    'en'                    => 'Coal',
                    'fr'                    => 'Charbon',
                    'ar'                    => 'فحم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Cobalt',
                    'en'                    => 'Cobalt',
                    'fr'                    => 'Cobalt',
                    'ar'                    => 'كوبالت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Coffee',
                    'en'                    => 'Coffee',
                    'fr'                    => 'Café',
                    'ar'                    => 'البن',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Coked coal',
                    'en'                    => 'Coked coal',
                    'fr'                    => 'Charbon à coke',
                    'ar'                    => 'فحم الكوك',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Concentrated coking coal',
                    'en'                    => 'Concentrated coking coal',
                    'fr'                    => 'Charbon cokéfiant concenntré',
                    'ar'                    => 'فحم الكوك المركّز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Copper',
                    'en'                    => 'Copper',
                    'fr'                    => 'Cuivre',
                    'ar'                    => 'نحاس',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Corundum',
                    'en'                    => 'Corundum',
                    'fr'                    => 'Corindon',
                    'ar'                    => 'كوروند',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Cotton',
                    'en'                    => 'Cotton',
                    'fr'                    => 'Cotton',
                    'ar'                    => 'قطن',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Coltan',
                    'en'                    => 'Coltan',
                    'fr'                    => 'Coltan',
                    'ar'                    => 'كولتان',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Diamonds',
                    'en'                    => 'Diamonds',
                    'fr'                    => 'Diamant',
                    'ar'                    => 'ألماس',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Diatomite',
                    'en'                    => 'Diatomite',
                    'fr'                    => 'Diatomite',
                    'ar'                    => 'تراب المشطورات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Dolomite',
                    'en'                    => 'Dolomite',
                    'fr'                    => 'Dolomite',
                    'ar'                    => 'دولوميت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Dysprosium',
                    'en'                    => 'Dysprosium',
                    'fr'                    => 'Dysprosium',
                    'ar'                    => 'ديسبروسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Emerald',
                    'en'                    => 'Emerald',
                    'fr'                    => 'Émeraude',
                    'ar'                    => 'زمرد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Erbium',
                    'en'                    => 'Erbium',
                    'fr'                    => 'Erbium',
                    'ar'                    => 'إربيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Eucalyptus',
                    'en'                    => 'Eucalyptus',
                    'fr'                    => 'Eucalyptus',
                    'ar'                    => 'أوكالبتوس',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Europium',
                    'en'                    => 'Europium',
                    'fr'                    => 'Europium',
                    'ar'                    => 'يوروبيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Felspar',
                    'en'                    => 'Felspar',
                    'fr'                    => 'Feldspath',
                    'ar'                    => 'فلدسبار',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferrochrome',
                    'en'                    => 'Ferrochrome',
                    'fr'                    => 'Ferrochrome',
                    'ar'                    => 'سبيكة من الكروم والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferromanganese',
                    'en'                    => 'Ferromanganese',
                    'fr'                    => 'Ferromanganèse',
                    'ar'                    => 'سبيكة من المنغنيز والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferromolybdenum',
                    'en'                    => 'Ferromolybdenum',
                    'fr'                    => 'Ferromolybdène',
                    'ar'                    => 'جميع المستندات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferronickel',
                    'en'                    => 'Ferronickel',
                    'fr'                    => 'Ferronickel',
                    'ar'                    => 'سبيكة من النيكل والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferroniobium',
                    'en'                    => 'Ferroniobium',
                    'fr'                    => 'Ferroniobium',
                    'ar'                    => 'سبيكة من النيوبيوم والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferrosilicon',
                    'en'                    => 'Ferrosilicon',
                    'fr'                    => 'Ferrosilicium',
                    'ar'                    => 'سبيكة من النيوبيوم والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Ferrotitanium',
                    'en'                    => 'Ferrotitanium',
                    'fr'                    => 'Ferrotitane',
                    'ar'                    => 'سبيكة من السيليكون والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferrotungsten',
                    'en'                    => 'Ferrotungsten',
                    'fr'                    => 'Ferro-tungstène',
                    'ar'                    => 'سبيكة من التنغستن والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ferrovanadium',
                    'en'                    => 'Ferrovanadium',
                    'fr'                    => 'Ferrovanadium',
                    'ar'                    => 'سبيكة من الفاناديوم والحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Fluorite (fluorspar)',
                    'en'                    => 'Fluorite (fluorspar)',
                    'fr'                    => 'Fluorite',
                    'ar'                    => 'فلوريت (فلورسبار)',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Fluorspar',
                    'en'                    => 'Fluorspar',
                    'fr'                    => 'Fluorine',
                    'ar'                    => 'فلورسبار',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Food crops',
                    'en'                    => 'Food crops',
                    'fr'                    => 'Cultures vivrières',
                    'ar'                    => 'محاصيل غذائية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Fossil coal',
                    'en'                    => 'Fossil coal',
                    'fr'                    => 'Charbon fossile',
                    'ar'                    => 'فحم أحفوري',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Frac Sand',
                    'en'                    => 'Frac Sand',
                    'fr'                    => 'Sable de fracturation',
                    'ar'                    => 'رمل التصديع',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Gadolinium',
                    'en'                    => 'Gadolinium',
                    'fr'                    => 'Gadolinium',
                    'ar'                    => 'غادولينيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Gallium',
                    'en'                    => 'Gallium',
                    'fr'                    => 'Gallium',
                    'ar'                    => 'غاليوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Garnet',
                    'en'                    => 'Garnet',
                    'fr'                    => 'Grenat',
                    'ar'                    => 'غارنيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Gas',
                    'en'                    => 'Gas',
                    'fr'                    => 'Gaz',
                    'ar'                    => 'غاز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Germanium',
                    'en'                    => 'Germanium',
                    'fr'                    => 'Germanium',
                    'ar'                    => 'جرمانيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Gold',
                    'en'                    => 'Gold',
                    'fr'                    => 'Or',
                    'ar'                    => 'ذهب',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Grain legumes (Pulses)',
                    'en'                    => 'Grain legumes (Pulses)',
                    'fr'                    => 'Légumineuses (Légumes-gousses)',
                    'ar'                    => 'بقول',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Granite',
                    'en'                    => 'Granite',
                    'fr'                    => 'Granite',
                    'ar'                    => 'غرانيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Graphite',
                    'en'                    => 'Graphite',
                    'fr'                    => 'Graphite',
                    'ar'                    => 'غرافيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Groundnuts',
                    'en'                    => 'Groundnuts',
                    'fr'                    => 'Arachide',
                    'ar'                    => 'فول سوداني',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 

                 [
                    'slug'                  => 'Gypsum',
                    'en'                    => 'Gypsum',
                    'fr'                    => 'Gypse',
                    'ar'                    => 'جص',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Hafnium',
                    'en'                    => 'Hafnium',
                    'fr'                    => 'Hafnium',
                    'ar'                    => 'هافنيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Heavy Mineral Sands',
                    'en'                    => 'Heavy Mineral Sands',
                    'fr'                    => 'Sables à minéraux lourds',
                    'ar'                    => 'الرمال المعدنية الثقيلة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Heavy Rare Earths and Yttrium',
                    'en'                    => 'Heavy Rare Earths and Yttrium',
                    'fr'                    => 'Terres rares lourdes et yttrium',
                    'ar'                    => 'الأتربة النادرة الثقيلة وإتريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Hematite',
                    'en'                    => 'Hematite',
                    'fr'                    => 'Hématite',
                    'ar'                    => 'هيماتيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Holmium',
                    'en'                    => 'Holmium',
                    'fr'                    => 'Holmium',
                    'ar'                    => 'هولميوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Hydrocarbons',
                    'en'                    => 'Hydrocarbons',
                    'fr'                    => 'Hydrocarbures',
                    'ar'                    => 'هيدروكربون',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ilmenite',
                    'en'                    => 'Ilmenite',
                    'fr'                    => 'Ilménite',
                    'ar'                    => 'إيلمنيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                 [
                    'slug'                  => 'Indium',
                    'en'                    => 'Indium',
                    'fr'                    => 'Indium',
                    'ar'                    => 'إنديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Iodine',
                    'en'                    => 'Iodine',
                    'fr'                    => 'Iode',
                    'ar'                    => 'يود',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Iridium',
                    'en'                    => 'Iridium',
                    'fr'                    => 'Iridium',
                    'ar'                    => 'إريديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Iron',
                    'en'                    => 'Iron',
                    'fr'                    => 'Fer',
                    'ar'                    => 'حديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Iron Ore',
                    'en'                    => 'Iron Ore',
                    'fr'                    => 'Minerai de fer',
                    'ar'                    => 'خام الحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 

                [
                    'slug'                  => 'Iron Sand',
                    'en'                    => 'Iron Sand',
                    'fr'                    => 'Sable de minéraux ferreux',
                    'ar'                    => 'رمال الحديد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Jade',
                    'en'                    => 'Jade',
                    'fr'                    => 'Jade',
                    'ar'                    => 'يشب',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Jatropha curcas',
                    'en'                    => 'Jatropha curcas',
                    'fr'                    => 'Jatropha curcas',
                    'ar'                    => 'يطروفة القحطة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Kaolin',
                    'en'                    => 'Kaolin',
                    'fr'                    => 'Kaolin',
                    'ar'                    => 'كاولين',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lanthanides',
                    'en'                    => 'Lanthanides',
                    'fr'                    => 'Lanthanides',
                    'ar'                    => 'لانثانيدات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lanthanum',
                    'en'                    => 'Lanthanum',
                    'fr'                    => 'Lanthane',
                    'ar'                    => 'لانثانوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lead',
                    'en'                    => 'Lead',
                    'fr'                    => 'Plomb',
                    'ar'                    => 'رصاص',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Leucoxene',
                    'en'                    => 'Leucoxene',
                    'fr'                    => 'Leucoxène',
                    'ar'                    => 'لوكوسين',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Light Rare Earths',
                    'en'                    => 'Light Rare Earths',
                    'fr'                    => 'Terres rares légères',
                    'ar'                    => 'الأتربة النادرة الخفيفة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lime',
                    'en'                    => 'Lime',
                    'fr'                    => 'Chaux',
                    'ar'                    => 'جير',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lime Sands',
                    'en'                    => 'Lime Sands',
                    'fr'                    => 'Sable à chaux',
                    'ar'                    => 'الرمال الجيرية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Limestone',
                    'en'                    => 'Limestone',
                    'fr'                    => 'Calcaire',
                    'ar'                    => 'حجر جير',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lithium',
                    'en'                    => 'Lithium',
                    'fr'                    => 'Lithium',
                    'ar'                    => 'ليثيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Lutetium',
                    'en'                    => 'Lutetium',
                    'fr'                    => 'Lutécium',
                    'ar'                    => 'لوتيشيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 

                [
                    'slug'                  => 'Magnesite',
                    'en'                    => 'Magnesite',
                    'fr'                    => 'Magnésite',
                    'ar'                    => 'كربونات المغنيسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Magnesium',
                    'en'                    => 'Magnesium',
                    'fr'                    => 'Magnésium',
                    'ar'                    => 'مغنيسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Magnesium Chloride',
                    'en'                    => 'Magnesium Chloride',
                    'fr'                    => 'Chlorure de magnésium',
                    'ar'                    => 'كلوريد المغنيسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Magnetite',
                    'en'                    => 'Magnetite',
                    'fr'                    => 'Magnétite',
                    'ar'                    => 'أكسيد الحديد الأسود',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Maize (Corn)',
                    'en'                    => 'Maize (Corn)',
                    'fr'                    => 'Maïs (blé)',
                    'ar'                    => 'ذرة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Manganese',
                    'en'                    => 'Manganese',
                    'fr'                    => 'Manganèse',
                    'ar'                    => 'منغنيز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Manganese Ore',
                    'en'                    => 'Manganese Ore',
                    'fr'                    => 'Minerai de manganèse',
                    'ar'                    => 'خام المنغنيز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Marble',
                    'en'                    => 'Marble',
                    'fr'                    => 'Marbre',
                    'ar'                    => 'رخام',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Medicinal plants',
                    'en'                    => 'Medicinal plants',
                    'fr'                    => 'Plantes médicinales',
                    'ar'                    => 'الأعشاب الطبية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Mercury',
                    'en'                    => 'Mercury',
                    'fr'                    => 'Mercure',
                    'ar'                    => 'زئبق',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Metallurgical/Coking Coal',
                    'en'                    => 'Metallurgical/Coking Coal',
                    'fr'                    => 'Coke de sidérurgie',
                    'ar'                    => 'فحم الكوك /الفحم المعدني',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Mica',
                                       'en' => 'Mica',
                                       'fr' => 'Mica',
                                       'ar' => 'ميكا',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Molybdenum',
                    'en'                    => 'Molybdenum',
                    'fr'                    => 'Molybdène',
                    'ar'                    => 'موليبدنوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Monazite',
                    'en'                    => 'Monazite',
                    'fr'                    => 'Monazite',
                    'ar'                    => 'مونازيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Neodymium',
                    'en'                    => 'Neodymium',
                    'fr'                    => 'Néodyme',
                    'ar'                    => 'نيوديميوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Nickel',
                    'en'                    => 'Nickel',
                    'fr'                    => 'Nickel',
                    'ar'                    => 'نيكل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Nickel Pig Iron',
                    'en'                    => 'Nickel Pig Iron',
                    'fr'                    => 'Nickel ferreux de basse qualité',
                    'ar'                    => 'سبيكة من حديد الزهر والنيكل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Niobium',
                    'en'                    => 'Niobium',
                    'fr'                    => 'Niobium',
                    'ar'                    => 'نيوبيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Not Specified',
                    'en'                    => 'Not Specified',
                    'fr'                    => 'Non précisé',
                    'ar'                    => 'غير محدد',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Oil',
                    'en'                    => 'Oil',
                    'fr'                    => 'Huile',
                    'ar'                    => 'زيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Oil crops',
                    'en'                    => 'Oil crops',
                    'fr'                    => 'Oléagineux',
                    'ar'                    => 'المحاصيل الزيتية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Oil palm or palm oils',
                    'en'                    => 'Oil palm or palm oils',
                    'fr'                    => 'Huile de palme',
                    'ar'                    => 'زيت النخيل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Oil palm products',
                    'en'                    => 'Oil palm products',
                    'fr'                    => 'Dérivés d\'huile de palme',
                    'ar'                    => 'منتجات زيت النخيل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Oilseeds',
                    'en'                    => 'Oilseeds',
                    'fr'                    => 'Graines oléagineuses',
                    'ar'                    => 'بذور زيتية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Opal',
                                       'en' => 'Opal',
                    'fr'                    => 'Opale',
                    'ar'                    => 'أوبال',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],
                [
                    'slug'                  => 'Osmium',
                    'en'                    => 'Osmium',
                    'fr'                    => 'Osmium',
                    'ar'                    => 'أوزميوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],  
                [
                    'slug'                  => 'Palladium',
                    'en'                    => 'Palladium',
                    'fr'                    => 'Palladium',
                    'ar'                    => 'بالاديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Palm oil',
                    'en'                    => 'Palm oil',
                    'fr'                    => 'Huile de palme',
                    'ar'                    => 'زيت النخيل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Perlite',
                    'en'                    => 'Perlite',
                    'fr'                    => 'Perlite',
                    'ar'                    => 'برليت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Phosphate',
                    'en'                    => 'Phosphate',
                    'fr'                    => 'Phosphate',
                    'ar'                    => 'فوسفات',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Platinum',
                    'en'                    => 'Platinum',
                    'fr'                    => 'Platine',
                    'ar'                    => 'بلاتين',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Platinum Group Metals',
                    'en'                    => 'Platinum Group Metals',
                    'fr'                    => 'Métaux du groupe du platine',
                    'ar'                    => 'مجموعة المعادن البلاتينية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Potash',
                    'en'                    => 'Potash',
                    'fr'                    => 'Potasse',
                    'ar'                    => 'بوتاس',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Potassium Chloride',
                    'en'                    => 'Potassium Chloride',
                    'fr'                    => 'Chlorure de potassium',
                    'ar'                    => 'كلوريد البوتاسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Potassium Nitrate',
                    'en'                    => 'Potassium Nitrate',
                    'fr'                    => 'Nitrate de potassium',
                    'ar'                    => 'نترات البوتاسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Potassium Oxide',
                    'en'                    => 'Potassium Oxide',
                    'fr'                    => 'Oxyde de potassium',
                    'ar'                    => 'أكسيد البوتاسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Potassium Sulfate',
                    'en'                    => 'Potassium Sulfate',
                    'fr'                    => 'Sulfate de potassium ',
                    'ar'                    => 'كبريتات البوتاسيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Praseodymium',
                    'en'                    => 'Praseodymium',
                    'fr'                    => 'Praséodyme',
                    'ar'                    => 'براسوديميوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Promethium',
                    'en'                    => 'Promethium',
                    'fr'                    => 'Prométhium',
                    'ar'                    => 'بروميثيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Pyrite',
                    'en'                    => 'Pyrite',
                    'fr'                    => 'Pyrite',
                    'ar'                    => 'بيريت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Quarried products',
                    'en'                    => 'Quarried products',
                    'fr'                    => 'Produits de carrière',
                    'ar'                    => 'منتجات المقالع',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rare Earth Elements',
                    'en'                    => 'Rare Earth Elements',
                    'fr'                    => 'Terres rares',
                    'ar'                    => 'عناصر أرضية نادرة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rhenium',
                    'en'                    => 'Rhenium',
                    'fr'                    => 'Rhénium',
                    'ar'                    => 'رينيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rhodium',
                    'en'                    => 'Rhodium',
                    'fr'                    => 'Rhodium',
                    'ar'                    => 'روديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Rice',
                    'en'                    => 'Rice',
                    'fr'                    => 'Riz',
                    'ar'                    => 'أرز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rice products',
                    'en'                    => 'Rice products',
                    'fr'                    => 'Dérivés du riz',
                    'ar'                    => 'منتجات الأرز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Rubber',
                    'en'                    => 'Rubber',
                    'fr'                    => 'Caoutchouc',
                    'ar'                    => 'مطاط',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rubber products',
                    'en'                    => 'Rubber products',
                    'fr'                    => 'Dérivés du caoutchouc',
                    'ar'                    => 'منتجات مطاطية',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Rubidium',
                    'en'                    => 'Rubidium',
                    'fr'                    => 'Rubidium',
                    'ar'                    => 'روبيديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ruby',
                    'en'                    => 'Ruby',
                    'fr'                    => 'Rubis',
                    'ar'                    => 'ياقوت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Ruthenium',
                    'en'                    => 'Ruthenium',
                    'fr'                    => 'Ruthénium',
                    'ar'                    => 'روثينيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Rutile',
                    'en'                    => 'Rutile',
                    'fr'                    => 'Rutile',
                    'ar'                    => 'روتيل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Safflower',
                    'en'                    => 'Safflower',
                    'fr'                    => 'Carthame',
                    'ar'                    => 'عصفر',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Salt',
                    'en'                    => 'Salt',
                    'fr'                    => 'Sel',
                    'ar'                    => 'ملح',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Samarium',
                    'en'                    => 'Samarium',
                    'fr'                    => 'Samarium',
                    'ar'                    => 'ساماريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sandstone',
                    'en'                    => 'Sandstone',
                                       'fr' => 'Grès',
                    'ar'                    => 'حجر رملي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sapphire',
                    'en'                    => 'Sapphire',
                    'fr'                    => 'Saphir',
                    'ar'                    => 'ياقوت أزرق',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Scandium',
                    'en'                    => 'Scandium',
                    'fr'                    => 'Scandium',
                    'ar'                    => 'سكانديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Scheelite',
                    'en'                    => 'Scheelite',
                    'fr'                    => 'Scheelite',
                    'ar'                    => 'شيك',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Selenium',
                    'en'                    => 'Selenium',
                    'fr'                    => 'Sélénium',
                    'ar'                    => 'سيلينيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Semi-coked coal',
                    'en'                    => 'Semi-coked coal',
                    'fr'                    => 'Charbon semi-coke',
                    'ar'                    => 'فحم مكربن',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Sesame',
                    'en'                    => 'Sesame',
                    'fr'                    => 'Sésame',
                    'ar'                    => 'سمسم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Silica',
                    'en'                    => 'Silica',
                    'fr'                    => 'Silice',
                    'ar'                    => 'سيليكا',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Silica Sand',
                    'en'                    => 'Silica Sand',
                    'fr'                    => 'Sable de silice',
                    'ar'                    => 'رمل السيليكا',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Silicomanganese',
                    'en'                    => 'Silicomanganese',
                    'fr'                    => 'Silicomanganèse',
                    'ar'                    => 'سيليكون المنغنيز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Silver',
                    'en'                    => 'Silver',
                    'fr'                    => 'Argent',
                    'ar'                    => 'فضة',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Sodium Bicarbonate',
                    'en'                    => 'Sodium Bicarbonate',
                    'fr'                    => 'Bicarbonate de sodium',
                    'ar'                    => 'بيكربونات الصوديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Sodium Carbonate',
                    'en'                    => 'Sodium Carbonate',
                    'fr'                    => 'Carbonate de sodium',
                    'ar'                    => 'كربونات الصوديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Sodium Sulfate',
                    'en'                    => 'Sodium Sulfate',
                    'fr'                    => 'Sulfate de sodium',
                    'ar'                    => 'كبريتات الصوديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sorghum',
                    'en'                    => 'Sorghum',
                    'fr'                    => 'Sorghum',
                    'ar'                    => 'سورغم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Soy',
                    'en'                    => 'Soy',
                                       'fr' => 'Soja',
                                       'ar' => 'صويا',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Soybeans (Soya beans)',
                    'en'                    => 'Soybeans (Soya beans)',
                    'fr'                    => 'Graines de soja',
                    'ar'                    => 'فول الصويا',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Spodumene',
                    'en'                    => 'Spodumene',
                    'fr'                    => 'Spodumène',
                    'ar'                    => 'إسبودومين',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Steel',
                    'en'                    => 'Steel',
                    'fr'                    => 'Acier',
                    'ar'                    => 'فولاذ',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Strontium',
                    'en'                    => 'Strontium',
                    'fr'                    => 'Strontium',
                    'ar'                    => 'سترونشيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sugar',
                    'en'                    => 'Sugar',
                    'fr'                    => 'Sucre',
                    'ar'                    => 'سكر',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Sugarcane',
                    'en'                    => 'Sugarcane',
                    'fr'                    => 'Canne à sucre',
                    'ar'                    => 'قصب السكر',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sulfur',
                    'en'                    => 'Sulfur',
                    'fr'                    => 'Sulfure',
                    'ar'                    => 'كبريت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Sulfuric Acid',
                    'en'                    => 'Sulfuric Acid',
                    'fr'                    => 'Acide sulfurique',
                    'ar'                    => 'حمض الكبريت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Synthetic Rutile',
                    'en'                    => 'Synthetic Rutile',
                    'fr'                    => 'Rutile synthétique',
                    'ar'                    => 'روتيل اصطناعي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Talc',
                    'en'                    => 'Talc',
                    'fr'                    => 'Talc',
                    'ar'                    => 'طلق',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Tantalum',
                    'en'                    => 'Tantalum',
                    'fr'                    => 'Tantale',
                    'ar'                    => 'تانتالوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Tanzanite',
                    'en'                    => 'Tanzanite',
                    'fr'                    => 'Tanzanite',
                    'ar'                    => 'تنزانيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Tea',
                    'en'                    => 'Tea',
                    'fr'                    => 'Thé',
                    'ar'                    => 'شاي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Teak (Tectona grandis)',
                    'en'                    => 'Teak (Tectona grandis)',
                    'fr'                    => 'Teck (Tectona grandis)',
                    'ar'                    => 'شجر التيك (ساج كبير)',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Tellurium',
                    'en'                    => 'Tellurium',
                    'fr'                    => 'Tellure',
                    'ar'                    => 'تيلوريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Terbium',
                    'en'                    => 'Terbium',
                    'fr'                    => 'Terbium',
                    'ar'                    => 'تربيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Theobroma cacao (Cocoa plant)',
                    'en'                    => 'Theobroma cacao (Cocoa plant)',
                    'fr'                    => 'Cacaotier (Theobroma cacao)',
                    'ar'                    => 'شجرة الكاكاو',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Thermal Coal',
                    'en'                    => 'Thermal Coal',
                    'fr'                    => 'Charbon thermique',
                    'ar'                    => 'فحم حراري',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Thorium',
                    'en'                    => 'Thorium',
                    'fr'                    => 'Thorium',
                    'ar'                    => 'ثوريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Thulium',
                    'en'                    => 'Thulium',
                    'fr'                    => 'Thulium',
                    'ar'                    => 'ثوليوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Timber',
                    'en'                    => 'Timber',
                    'fr'                    => 'Bois de mine',
                    'ar'                    => 'خشب إنشائي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Timber (Wood)',
                    'en'                    => 'Timber (Wood)',
                    'fr'                    => 'Bois de charpente',
                    'ar'                    => 'خشب',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Tin',
                    'en'                    => 'Tin',
                    'fr'                    => 'Étain',
                    'ar'                    => 'قصدير',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Titanium',
                    'en'                    => 'Titanium',
                    'fr'                    => 'Titane',
                    'ar'                    => 'تيتانيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Titanium Sponge',
                    'en'                    => 'Titanium Sponge',
                    'fr'                    => 'Éponge de titane',
                    'ar'                    => 'تيتانيوم اسفنجي',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Topaz',
                    'en'                    => 'Topaz',
                    'fr'                    => 'Topaze',
                    'ar'                    => 'توباز',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Tungsten',
                    'en'                    => 'Tungsten',
                    'fr'                    => 'Tungstène',
                    'ar'                    => 'تنغستن',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Uranium (U3O8)',
                    'en'                    => 'Uranium (U3O8)',
                    'fr'                    => 'Octaoxyde de triuranium',
                    'ar'                    => 'يورانيوم (U3O8)',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Value-added crops',
                    'en'                    => 'Value-added crops',
                    'fr'                    => 'Cultures à valeur ajoutée ',
                    'ar'                    => 'قيمة مضافة للمحاصيل',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Vanadium',
                    'en'                    => 'Vanadium',
                    'fr'                    => 'Vanadium',
                    'ar'                    => 'فاناديوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Vermiculite',
                    'en'                    => 'Vermiculite',
                    'fr'                    => 'Vermiculite',
                    'ar'                    => 'فيرميكوليت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Wollastonite',
                    'en'                    => 'Wollastonite',
                    'fr'                    => 'Wollastonite',
                    'ar'                    => 'ولستونيت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Ytterbium',
                    'en'                    => 'Ytterbium',
                    'fr'                    => 'Ytterbium',
                    'ar'                    => 'إتيربيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Yttrium',
                    'en'                    => 'Yttrium',
                    'fr'                    => 'Yttrium',
                    'ar'                    => 'إتريوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Zeolites',
                    'en'                    => 'Zeolites',
                    'fr'                    => 'Zéolithes',
                    'ar'                    => 'زيوليت',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Zinc',
                    'en'                    => 'Zinc',
                    'fr'                    => 'Zinc',
                    'ar'                    => 'زنك',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
  [
                    'slug'                  => 'Zinc-Lead',
                    'en'                    => 'Zinc-Lead',
                    'fr'                    => 'Plomb allié au zinc',
                    'ar'                    => 'سبيكة من الزنك والرصاص',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Zircon',
                    'en'                    => 'Zircon',
                    'fr'                    => 'Zircon',
                    'ar'                    => 'زركون',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Zirconium',
                    'en'                    => 'Zirconium',
                    'fr'                    => 'Zirconium',
                    'ar'                    => 'زركونيوم',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Tobacco',
                    'en'                    => 'Tobacco',
                    'fr'                    => 'Tabac',
                    'ar'                    => null,
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Solar energy',
                    'en'                    => 'Solar energy',
                    'fr'                    => 'Energie solaire',
                    'ar'                    => null,
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Wind energy',
                    'en'                    => 'Wind energy',
                    'fr'                    => 'Énergie éolienne',
                    'ar'                    => null,
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],
                [
                    'slug'                  => 'Coke',
                    'en'                    => 'Coke',
                    'fr'                    => 'Coke',
                    'ar'                    => 'كوك',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],
                [
                    'slug'                  => 'Other crops',
                    'en'                    => 'Other crops',
                    'fr'                    => 'Autres cultures',
                    'ar'                    => 'محاصيل أخرى',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],  
                [
                    'slug'                  => 'Other',
                    'en'                    => 'Other',
                    'fr'                    => 'Autres',
                    'ar'                    => 'أخر',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ], 
                [
                    'slug'                  => 'Other minerals',
                    'en'                    => 'Other minerals',
                    'fr'                    => 'Autres minéraux',
                    'ar'                    => 'المعادن الأخرى',
                    'created_at'            => new DateTime,
                    'updated_at'            => new DateTime,
                ],
            ]
        );
    }
}