<?php
return [
    /**
     * Roles for different type of users.
     */
    'roles'    => [
        'superadmin'         => [
            'name'         => 'superadmin',
            'display_name' => 'Super Administrator',
            'description'  => 'NRGI staff, CCSI - Columbia university'
        ],
        'admin'              => [
            'name'         => 'admin',
            'display_name' => 'Country/national Administrator',
            'description'  => 'National administrator should be able to approve the data uploaded by the research associate.'
        ],
        'research_associate' => [
            'name'         => 'research_associate',
            'display_name' => 'Research Associate',
            'description'  => '(graduate student, interns) to upload contract, provide metadata, annotate. Should be able to edit the data entered by others.'
        ],
    ],
    'country'  => [
        1   => ['name' => 'Afganistan', 'code' => 'AFG'],
        2   => ['name' => 'Albania', 'code' => 'ALB'],
        3   => ['name' => 'Algeria', 'code' => 'DZA'],
        4   => ['name' => 'American Samoa', 'code' => 'ASM'],
        5   => ['name' => 'Andorra', 'code' => 'AND'],
        6   => ['name' => 'Angola', 'code' => 'AGO'],
        7   => ['name' => 'Anguilla', 'code' => 'AIA'],
        8   => ['name' => 'Antigua & Barbuda', 'code' => 'ATG'],
        9   => ['name' => 'Argentina', 'code' => 'ARG'],
        10  => ['name' => 'Armenia', 'code' => 'ARM'],
        11  => ['name' => 'Aruba', 'code' => 'ABW'],
        12  => ['name' => 'Australia', 'code' => 'AUS'],
        13  => ['name' => 'Austria', 'code' => 'AUT'],
        14  => ['name' => 'Azerbaijan', 'code' => 'AZE'],
        15  => ['name' => 'Bahamas', 'code' => 'BHS'],
        16  => ['name' => 'Bahrain', 'code' => 'BHR'],
        17  => ['name' => 'Bangladesh', 'code' => 'BGD'],
        18  => ['name' => 'Barbados', 'code' => 'BRB'],
        19  => ['name' => 'Belarus', 'code' => 'BLR'],
        20  => ['name' => 'Belgium', 'code' => 'BEL'],
        21  => ['name' => 'Belize', 'code' => 'BLZ'],
        22  => ['name' => 'Benin', 'code' => 'BEN'],
        23  => ['name' => 'Bermuda', 'code' => 'BMU'],
        24  => ['name' => 'Bhutan', 'code' => 'BTN'],
        25  => ['name' => 'Bolivia', 'code' => 'BOL'],
        26  => ['name' => 'Bonaire', 'code' => 'BES'],
        27  => ['name' => 'Bosnia-Herzegovina', 'code' => 'BIH'],
        28  => ['name' => 'Botswana', 'code' => 'BWA'],
        29  => ['name' => 'Brazil', 'code' => 'BRA'],
        30  => ['name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
        31  => ['name' => 'British Virgin Islands', 'code' => 'VGB'],
        32  => ['name' => 'Brunei Darussalam', 'code' => 'BRN'],
        33  => ['name' => 'Bulgaria', 'code' => 'BGR'],
        34  => ['name' => 'Burkina Faso', 'code' => 'BFA'],
        35  => ['name' => 'Burundi', 'code' => 'BDI'],
        36  => ['name' => 'Cambodia', 'code' => 'KHM'],
        37  => ['name' => 'Cameroon', 'code' => 'CMR'],
        38  => ['name' => 'Canada', 'code' => 'CAN'],
        39  => ['name' => 'Cape Verde Islands', 'code' => 'CPV'],
        40  => ['name' => 'Cayman Islands', 'code' => 'CYM'],
        41  => ['name' => 'Central African Republic', 'code' => 'CAF'],
        42  => ['name' => 'Chad', 'code' => 'TCD'],
        43  => ['name' => 'Chile', 'code' => 'CHL'],
        44  => ['name' => 'China', 'code' => 'CHN'],
        45  => ['name' => 'Christmas Island', 'code' => 'CXR'],
        46  => ['name' => 'Cocos (Keeling) Islands', 'code' => 'CCK'],
        47  => ['name' => 'Colombia', 'code' => 'COL'],
        48  => ['name' => 'Comoros', 'code' => 'COM'],
        49  => ['name' => 'Congo (Brazzaville)', 'code' => 'COG'],
        50  => ['name' => 'Congo (Kinshasa)', 'code' => 'ZAR'],
        51  => ['name' => 'Cook Islands', 'code' => 'COK'],
        52  => ['name' => 'Costa Rica', 'code' => 'CRI'],
        53  => ['name' => 'Croatia', 'code' => 'HRV'],
        54  => ['name' => 'Cuba', 'code' => 'CUB'],
        55  => ['name' => 'CuraÃ§ao', 'code' => 'CUW'],
        56  => ['name' => 'Cyprus', 'code' => 'CYP'],
        57  => ['name' => 'Czech Republic', 'code' => 'CZE'],
        58  => ['name' => 'Denmark', 'code' => 'DNK'],
        59  => ['name' => 'Djibouti', 'code' => 'DJI'],
        60  => ['name' => 'Dominica', 'code' => 'DMA'],
        61  => ['name' => 'Dominican Republic', 'code' => 'DOM'],
        62  => ['name' => 'East Timor', 'code' => 'TLS'],
        63  => ['name' => 'Ecuador', 'code' => 'ECU'],
        64  => ['name' => 'Egypt', 'code' => 'EGY'],
        65  => ['name' => 'El Salvador', 'code' => 'SLV'],
        66  => ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
        67  => ['name' => 'Eritrea', 'code' => 'ERI'],
        68  => ['name' => 'Estonia', 'code' => 'EST'],
        69  => ['name' => 'Ethiopia', 'code' => 'ETH'],
        70  => ['name' => 'Faeroe Islands', 'code' => 'FRO'],
        71  => ['name' => 'Falkland Islands', 'code' => 'FLK'],
        72  => ['name' => 'Fiji', 'code' => 'FJI'],
        73  => ['name' => 'Finland', 'code' => 'FIN'],
        74  => ['name' => 'France', 'code' => 'FRA'],
        75  => ['name' => 'French Guiana', 'code' => 'GUF'],
        76  => ['name' => 'French Polynesia', 'code' => 'PYF'],
        77  => ['name' => 'French Southern Territories', 'code' => 'ATF'],
        78  => ['name' => 'Gabon', 'code' => 'GAB'],
        79  => ['name' => 'Gambia', 'code' => 'GMB'],
        80  => ['name' => 'Georgia', 'code' => 'GEO'],
        81  => ['name' => 'Germany', 'code' => 'DEU'],
        82  => ['name' => 'Ghana', 'code' => 'GHA'],
        83  => ['name' => 'Gibralter', 'code' => 'GIB'],
        84  => ['name' => 'Greece', 'code' => 'GRC'],
        85  => ['name' => 'Greenland', 'code' => 'GRL'],
        86  => ['name' => 'Grenada', 'code' => 'GRD'],
        87  => ['name' => 'Guadeloupe', 'code' => 'GLP'],
        88  => ['name' => 'Guam', 'code' => 'GUM'],
        89  => ['name' => 'Guatemala', 'code' => 'GTM'],
        90  => ['name' => 'Guernsey', 'code' => 'GGY'],
        91  => ['name' => 'Guinea', 'code' => 'GIN'],
        92  => ['name' => 'Guinea-Bissau', 'code' => 'GNB'],
        93  => ['name' => 'Guyana', 'code' => 'GUY'],
        94  => ['name' => 'Haiti', 'code' => 'HTI'],
        95  => ['name' => 'Holy See', 'code' => 'VAT'],
        96  => ['name' => 'Honduras', 'code' => 'HND'],
        97  => ['name' => 'Hong Kong', 'code' => 'HKG'],
        98  => ['name' => 'Hungary', 'code' => 'HUN'],
        99  => ['name' => 'Iceland', 'code' => 'ISL'],
        100 => ['name' => 'India', 'code' => 'IND'],
        101 => ['name' => 'Indonesia', 'code' => 'IDN'],
        102 => ['name' => 'Iran', 'code' => 'IRN'],
        103 => ['name' => 'Iraq', 'code' => 'IRQ'],
        104 => ['name' => 'Ireland', 'code' => 'IRL'],
        105 => ['name' => 'Isle of Man', 'code' => 'IMN'],
        106 => ['name' => 'Israel', 'code' => 'ISR'],
        107 => ['name' => 'Italy', 'code' => 'ITA'],
        108 => ['name' => 'Ivory Coast', 'code' => 'CIV'],
        109 => ['name' => 'Jamaica', 'code' => 'JAM'],
        110 => ['name' => 'Japan', 'code' => 'JPN'],
        111 => ['name' => 'Jersey', 'code' => 'JEY'],
        112 => ['name' => 'Jordan', 'code' => 'JOR'],
        113 => ['name' => 'Kazakhstan', 'code' => 'KAZ'],
        114 => ['name' => 'Kenya', 'code' => 'KEN'],
        115 => ['name' => 'Kiribati', 'code' => 'KIR'],
        116 => ['name' => 'Kuwait', 'code' => 'KWT'],
        117 => ['name' => 'Kyrgyzstan', 'code' => 'KGZ'],
        118 => ['name' => 'Laos', 'code' => 'LAO'],
        119 => ['name' => 'Latvia', 'code' => 'LVA'],
        120 => ['name' => 'Lebanon', 'code' => 'LBN'],
        121 => ['name' => 'Lesotho', 'code' => 'LSO'],
        122 => ['name' => 'Liberia', 'code' => 'LBR'],
        123 => ['name' => 'Libya', 'code' => 'LBY'],
        124 => ['name' => 'Liechtenstein', 'code' => 'LIE'],
        125 => ['name' => 'Lithuania', 'code' => 'LTU'],
        126 => ['name' => 'Luxembourg', 'code' => 'LUX'],
        127 => ['name' => 'Macau', 'code' => 'MAC'],
        128 => ['name' => 'Macedonia', 'code' => 'MKD'],
        129 => ['name' => 'Madagascar', 'code' => 'MDG'],
        130 => ['name' => 'Malawi', 'code' => 'MWI'],
        131 => ['name' => 'Malaysia', 'code' => 'MYS'],
        132 => ['name' => 'Maldives', 'code' => 'MDV'],
        133 => ['name' => 'Mali', 'code' => 'MLI'],
        134 => ['name' => 'Malta', 'code' => 'MLT'],
        135 => ['name' => 'Marshall Islands', 'code' => 'MHL'],
        136 => ['name' => 'Martinique', 'code' => 'MTQ'],
        137 => ['name' => 'Mauritania', 'code' => 'MRT'],
        138 => ['name' => 'Mauritius', 'code' => 'MUS'],
        139 => ['name' => 'Mayotte', 'code' => 'MYT'],
        140 => ['name' => 'Mexico', 'code' => 'MEX'],
        141 => ['name' => 'Micronesia', 'code' => 'FSM'],
        142 => ['name' => 'Moldova', 'code' => 'MDA'],
        143 => ['name' => 'Monaco', 'code' => 'MCO'],
        144 => ['name' => 'Mongolia', 'code' => 'MNG'],
        145 => ['name' => 'Montenegro', 'code' => 'MNE'],
        146 => ['name' => 'Montserrat', 'code' => 'MSR'],
        147 => ['name' => 'Morocco', 'code' => 'MAR'],
        148 => ['name' => 'Mozambique', 'code' => 'MOZ'],
        149 => ['name' => 'Myanmar', 'code' => 'MMR'],
        150 => ['name' => 'Namibia', 'code' => 'NAM'],
        151 => ['name' => 'Nauru', 'code' => 'NRU'],
        152 => ['name' => 'Nepal', 'code' => 'NPL'],
        153 => ['name' => 'Netherlands Antilles', 'code' => 'ANT'],
        154 => ['name' => 'Netherlands', 'code' => 'NLD'],
        155 => ['name' => 'New Caledonia', 'code' => 'NCL'],
        156 => ['name' => 'New Zealand', 'code' => 'NZL'],
        157 => ['name' => 'Nicaragua', 'code' => 'NIC'],
        158 => ['name' => 'Niger', 'code' => 'NER'],
        159 => ['name' => 'Nigeria', 'code' => 'NGA'],
        160 => ['name' => 'Niue', 'code' => 'NIU'],
        161 => ['name' => 'Norfolk Island', 'code' => 'NFK'],
        162 => ['name' => 'North Korea', 'code' => 'PRK'],
        163 => ['name' => 'Northern Mariana Islands', 'code' => 'MNP'],
        164 => ['name' => 'Norway', 'code' => 'NOR'],
        165 => ['name' => 'Oman', 'code' => 'OMN'],
        166 => ['name' => 'Pakistan', 'code' => 'PAK'],
        167 => ['name' => 'Palau', 'code' => 'PLW'],
        168 => ['name' => 'Palestinian Territories', 'code' => 'PSE'],
        169 => ['name' => 'Panama', 'code' => 'PAN'],
        170 => ['name' => 'Papua New Guinea', 'code' => 'PNG'],
        171 => ['name' => 'Paraguay', 'code' => 'PRY'],
        172 => ['name' => 'Peru', 'code' => 'PER'],
        173 => ['name' => 'Philippines', 'code' => 'PHL'],
        174 => ['name' => 'Pitcairn Islands', 'code' => 'PCN'],
        175 => ['name' => 'Poland', 'code' => 'POL'],
        176 => ['name' => 'Portugal', 'code' => 'PRT'],
        177 => ['name' => 'Puerto Rico', 'code' => 'PRI'],
        178 => ['name' => 'Qatar', 'code' => 'QAT'],
        179 => ['name' => 'Romania', 'code' => 'ROU'],
        180 => ['name' => 'Russia', 'code' => 'RUS'],
        181 => ['name' => 'Rwanda', 'code' => 'RWA'],
        182 => ['name' => 'RÃ©union', 'code' => 'REU'],
        183 => ['name' => 'Saba', 'code' => 'BES'],
        184 => ['name' => 'Saint BarthÃ©lemy', 'code' => 'BLM'],
        185 => ['name' => 'Saint Christopher & Nevis', 'code' => 'KNA'],
        186 => ['name' => 'Saint Helena', 'code' => 'SHN'],
        187 => ['name' => 'Saint Lucia', 'code' => 'LCA'],
        188 => ['name' => 'Saint Martin', 'code' => 'MAF'],
        189 => ['name' => 'Saint Pierre & Miquelon', 'code' => 'SPM'],
        190 => ['name' => 'Saint Vincent & The Grenadines', 'code' => 'VCT'],
        191 => ['name' => 'Samoa', 'code' => 'WSM'],
        192 => ['name' => 'San Marino', 'code' => 'SMR'],
        193 => ['name' => 'Sao Tome & Principe', 'code' => 'STP'],
        194 => ['name' => 'Saudi Arabia', 'code' => 'SAU'],
        195 => ['name' => 'Senegal', 'code' => 'SEN'],
        196 => ['name' => 'Serbia', 'code' => 'SRB'],
        197 => ['name' => 'Seychelles', 'code' => 'SYC'],
        198 => ['name' => 'Sierra Leone', 'code' => 'SLE'],
        199 => ['name' => 'Singapore', 'code' => 'SGP'],
        200 => ['name' => 'Sint Eustatius', 'code' => 'BES'],
        201 => ['name' => 'Sint Maarten', 'code' => 'SXM'],
        202 => ['name' => 'Slovakia', 'code' => 'SVK'],
        203 => ['name' => 'Slovenia', 'code' => 'SVN'],
        204 => ['name' => 'Solomon Islands', 'code' => 'SLB'],
        205 => ['name' => 'Somalia', 'code' => 'SOM'],
        206 => ['name' => 'Somaliland', 'code' => 'SOM'],
        207 => ['name' => 'South Africa', 'code' => 'ZAF'],
        208 => ['name' => 'South Georgia & The South Sandwish Islands', 'code' => 'SGS'],
        209 => ['name' => 'South Korea', 'code' => 'KOR'],
        210 => ['name' => 'South Sudan', 'code' => 'SSD'],
        211 => ['name' => 'Spain', 'code' => 'ESP'],
        212 => ['name' => 'Sri Lanka', 'code' => 'LKA'],
        213 => ['name' => 'Sudan', 'code' => 'SDN'],
        214 => ['name' => 'Suriname', 'code' => 'SUR'],
        215 => ['name' => 'Swaziland', 'code' => 'SWZ'],
        216 => ['name' => 'Sweden', 'code' => 'SWE'],
        217 => ['name' => 'Switzerland', 'code' => 'CHE'],
        218 => ['name' => 'Syria', 'code' => 'SYR'],
        219 => ['name' => 'Taiwan', 'code' => 'TWN'],
        220 => ['name' => 'Tajikistan', 'code' => 'TJK'],
        221 => ['name' => 'Tanzania', 'code' => 'TZA'],
        222 => ['name' => 'Thailand', 'code' => 'THA'],
        223 => ['name' => 'Togo', 'code' => 'TGO'],
        224 => ['name' => 'Tokelau', 'code' => 'TKL'],
        225 => ['name' => 'Tonga', 'code' => 'TON'],
        226 => ['name' => 'Trinidad & Tobago', 'code' => 'TTO'],
        227 => ['name' => 'Tunisia', 'code' => 'TUN'],
        228 => ['name' => 'Turkey', 'code' => 'TUR'],
        229 => ['name' => 'Turkmenistan', 'code' => 'TKM'],
        230 => ['name' => 'Turks & Caicos Islands', 'code' => 'TCA'],
        231 => ['name' => 'Tuvalu', 'code' => 'TUV'],
        232 => ['name' => 'Uganda', 'code' => 'UGA'],
        233 => ['name' => 'Ukraine', 'code' => 'UKR'],
        234 => ['name' => 'United Arab Emirates', 'code' => 'ARE'],
        235 => ['name' => 'United Kingdom', 'code' => 'GBR'],
        236 => ['name' => 'United States', 'code' => 'USA'],
        237 => ['name' => 'United States Virgin Islands', 'code' => 'VIR'],
        238 => ['name' => 'Uruguay', 'code' => 'URY'],
        239 => ['name' => 'Uzbekistan', 'code' => 'UZB'],
        240 => ['name' => 'Vanuatu', 'code' => 'VUT'],
        241 => ['name' => 'Venezuela', 'code' => 'VEN'],
        242 => ['name' => 'Vietnam', 'code' => 'VNM'],
        243 => ['name' => 'Wallis & Futuna', 'code' => 'WLF'],
        244 => ['name' => 'Western Sahara', 'code' => 'ESH'],
        245 => ['name' => 'Yemen', 'code' => 'YEM'],
        246 => ['name' => 'Zambia', 'code' => 'ZMB'],
        247 => ['name' => 'Zimbabwe', 'code' => 'ZWE']
    ],
    'language' => [
        'EN' => 'English',
        'FR' => 'French',
    ],
    'resource' => [
        'Aluminium '            => 'Aluminium',
        'Base metals'           => 'Base metals',
        'Bauxite'               => 'Bauxit',
        'Coal'                  => 'Coal',
        'Cobalt'                => 'Cobal',
        'Copper'                => 'Copper',
        'Crude oil'             => 'Crud',
        'Diamonds'              => 'Diamonds',
        'Gas'                   => 'Ga',
        'Gold'                  => 'Gold',
        'Iron ore '             => 'Iron ore ',
        'Lapis lazuli'          => 'Lapis lazuli',
        'Lead'                  => 'Lead',
        'Lithium'               => 'Lithium',
        'Manganese'             => 'Manganese',
        'Molybdenum'            => 'Molybdenum',
        'Nickel'                => 'Nickel',
        'Phosphate rock'        => 'Phosphate rock',
        'Platinum Group Metals' => 'Platinum Group Metals',
        'Precious stones'       => 'Precious stones',
        'Quartz'                => 'Quartz',
        'Semi-precious stones'  => 'Semi-precious stones',
        'Silver'                => 'Silver',
        'Titanium'              => 'Titanium',
        'Uranium'               => 'Uranium',
        'Zinc'                  => 'Zinc',
        'Citrus'                => 'Citrus',
        'Food crops'            => 'Food crops',
        'Hydrocarbons'          => 'Hydrocarbons',
        'Palm oil'              => 'Palm oil',
        'Rubber'                => 'Rubber',
        'Soy'                   => 'Soy',
        'Sugar'                 => 'Sugar',
        'Timber'                => 'Timber'
    ]
];