<?php
return [
    /**
     * Roles for different type of users.
     */
    'roles'    => [
        'superadmin'         => [
            'name'         => 'superadmin',
            'display_name' => 'Super Administrator',
            'description'  => 'NRGI staff, CCSI - Columbia university'
        ],
        'admin'              => [
            'name'         => 'admin',
            'display_name' => 'Country/national Administrator',
            'description'  => 'National administrator should be able to approve the data uploaded by the research associate.'
        ],
        'research_associate' => [
            'name'         => 'research_associate',
            'display_name' => 'Research Associate',
            'description'  => '(graduate student, interns) to upload contract, provide metadata, annotate. Should be able to edit the data entered by others.'
        ],
    ],
    'country'  => [
        1   => ['id' => 1, 'name' => 'Afganistan', 'code' => 'AFG'],
        2   => ['id' => 2, 'name' => 'Albania', 'code' => 'ALB'],
        3   => ['id' => 3, 'name' => 'Algeria', 'code' => 'DZA'],
        4   => ['id' => 4, 'name' => 'American Samoa', 'code' => 'ASM'],
        5   => ['id' => 5, 'name' => 'Andorra', 'code' => 'AND'],
        6   => ['id' => 6, 'name' => 'Angola', 'code' => 'AGO'],
        7   => ['id' => 7, 'name' => 'Anguilla', 'code' => 'AIA'],
        8   => ['id' => 8, 'name' => 'Antigua & Barbuda', 'code' => 'ATG'],
        9   => ['id' => 9, 'name' => 'Argentina', 'code' => 'ARG'],
        10  => ['id' => 10, 'name' => 'Armenia', 'code' => 'ARM'],
        11  => ['id' => 11, 'name' => 'Aruba', 'code' => 'ABW'],
        12  => ['id' => 12, 'name' => 'Australia', 'code' => 'AUS'],
        13  => ['id' => 13, 'name' => 'Austria', 'code' => 'AUT'],
        14  => ['id' => 14, 'name' => 'Azerbaijan', 'code' => 'AZE'],
        15  => ['id' => 15, 'name' => 'Bahamas', 'code' => 'BHS'],
        16  => ['id' => 16, 'name' => 'Bahrain', 'code' => 'BHR'],
        17  => ['id' => 17, 'name' => 'Bangladesh', 'code' => 'BGD'],
        18  => ['id' => 18, 'name' => 'Barbados', 'code' => 'BRB'],
        19  => ['id' => 19, 'name' => 'Belarus', 'code' => 'BLR'],
        20  => ['id' => 20, 'name' => 'Belgium', 'code' => 'BEL'],
        21  => ['id' => 21, 'name' => 'Belize', 'code' => 'BLZ'],
        22  => ['id' => 22, 'name' => 'Benin', 'code' => 'BEN'],
        23  => ['id' => 23, 'name' => 'Bermuda', 'code' => 'BMU'],
        24  => ['id' => 24, 'name' => 'Bhutan', 'code' => 'BTN'],
        25  => ['id' => 25, 'name' => 'Bolivia', 'code' => 'BOL'],
        26  => ['id' => 26, 'name' => 'Bonaire', 'code' => 'BES'],
        27  => ['id' => 27, 'name' => 'Bosnia-Herzegovina', 'code' => 'BIH'],
        28  => ['id' => 28, 'name' => 'Botswana', 'code' => 'BWA'],
        29  => ['id' => 29, 'name' => 'Brazil', 'code' => 'BRA'],
        30  => ['id' => 30, 'name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
        31  => ['id' => 31, 'name' => 'British Virgin Islands', 'code' => 'VGB'],
        32  => ['id' => 32, 'name' => 'Brunei Darussalam', 'code' => 'BRN'],
        33  => ['id' => 33, 'name' => 'Bulgaria', 'code' => 'BGR'],
        34  => ['id' => 34, 'name' => 'Burkina Faso', 'code' => 'BFA'],
        35  => ['id' => 35, 'name' => 'Burundi', 'code' => 'BDI'],
        36  => ['id' => 36, 'name' => 'Cambodia', 'code' => 'KHM'],
        37  => ['id' => 37, 'name' => 'Cameroon', 'code' => 'CMR'],
        38  => ['id' => 38, 'name' => 'Canada', 'code' => 'CAN'],
        39  => ['id' => 39, 'name' => 'Cape Verde Islands', 'code' => 'CPV'],
        40  => ['id' => 40, 'name' => 'Cayman Islands', 'code' => 'CYM'],
        41  => ['id' => 41, 'name' => 'Central African Republic', 'code' => 'CAF'],
        42  => ['id' => 42, 'name' => 'Chad', 'code' => 'TCD'],
        43  => ['id' => 43, 'name' => 'Chile', 'code' => 'CHL'],
        44  => ['id' => 44, 'name' => 'China', 'code' => 'CHN'],
        45  => ['id' => 45, 'name' => 'Christmas Island', 'code' => 'CXR'],
        46  => ['id' => 46, 'name' => 'Cocos (Keeling) Islands', 'code' => 'CCK'],
        47  => ['id' => 47, 'name' => 'Colombia', 'code' => 'COL'],
        48  => ['id' => 48, 'name' => 'Comoros', 'code' => 'COM'],
        49  => ['id' => 49, 'name' => 'Congo (Brazzaville)', 'code' => 'COG'],
        50  => ['id' => 50, 'name' => 'Congo (Kinshasa)', 'code' => 'ZAR'],
        51  => ['id' => 51, 'name' => 'Cook Islands', 'code' => 'COK'],
        52  => ['id' => 52, 'name' => 'Costa Rica', 'code' => 'CRI'],
        53  => ['id' => 53, 'name' => 'Croatia', 'code' => 'HRV'],
        54  => ['id' => 54, 'name' => 'Cuba', 'code' => 'CUB'],
        55  => ['id' => 55, 'name' => 'CuraÃ§ao', 'code' => 'CUW'],
        56  => ['id' => 56, 'name' => 'Cyprus', 'code' => 'CYP'],
        57  => ['id' => 57, 'name' => 'Czech Republic', 'code' => 'CZE'],
        58  => ['id' => 58, 'name' => 'Denmark', 'code' => 'DNK'],
        59  => ['id' => 59, 'name' => 'Djibouti', 'code' => 'DJI'],
        60  => ['id' => 60, 'name' => 'Dominica', 'code' => 'DMA'],
        61  => ['id' => 61, 'name' => 'Dominican Republic', 'code' => 'DOM'],
        62  => ['id' => 62, 'name' => 'East Timor', 'code' => 'TLS'],
        63  => ['id' => 63, 'name' => 'Ecuador', 'code' => 'ECU'],
        64  => ['id' => 64, 'name' => 'Egypt', 'code' => 'EGY'],
        65  => ['id' => 65, 'name' => 'El Salvador', 'code' => 'SLV'],
        66  => ['id' => 66, 'name' => 'Equatorial Guinea', 'code' => 'GNQ'],
        67  => ['id' => 67, 'name' => 'Eritrea', 'code' => 'ERI'],
        68  => ['id' => 68, 'name' => 'Estonia', 'code' => 'EST'],
        69  => ['id' => 69, 'name' => 'Ethiopia', 'code' => 'ETH'],
        70  => ['id' => 70, 'name' => 'Faeroe Islands', 'code' => 'FRO'],
        71  => ['id' => 71, 'name' => 'Falkland Islands', 'code' => 'FLK'],
        72  => ['id' => 72, 'name' => 'Fiji', 'code' => 'FJI'],
        73  => ['id' => 73, 'name' => 'Finland', 'code' => 'FIN'],
        74  => ['id' => 74, 'name' => 'France', 'code' => 'FRA'],
        75  => ['id' => 75, 'name' => 'French Guiana', 'code' => 'GUF'],
        76  => ['id' => 76, 'name' => 'French Polynesia', 'code' => 'PYF'],
        77  => ['id' => 77, 'name' => 'French Southern Territories', 'code' => 'ATF'],
        78  => ['id' => 78, 'name' => 'Gabon', 'code' => 'GAB'],
        79  => ['id' => 79, 'name' => 'Gambia', 'code' => 'GMB'],
        80  => ['id' => 80, 'name' => 'Georgia', 'code' => 'GEO'],
        81  => ['id' => 81, 'name' => 'Germany', 'code' => 'DEU'],
        82  => ['id' => 82, 'name' => 'Ghana', 'code' => 'GHA'],
        83  => ['id' => 83, 'name' => 'Gibralter', 'code' => 'GIB'],
        84  => ['id' => 84, 'name' => 'Greece', 'code' => 'GRC'],
        85  => ['id' => 85, 'name' => 'Greenland', 'code' => 'GRL'],
        86  => ['id' => 86, 'name' => 'Grenada', 'code' => 'GRD'],
        87  => ['id' => 87, 'name' => 'Guadeloupe', 'code' => 'GLP'],
        88  => ['id' => 88, 'name' => 'Guam', 'code' => 'GUM'],
        89  => ['id' => 89, 'name' => 'Guatemala', 'code' => 'GTM'],
        90  => ['id' => 90, 'name' => 'Guernsey', 'code' => 'GGY'],
        91  => ['id' => 91, 'name' => 'Guinea', 'code' => 'GIN'],
        92  => ['id' => 92, 'name' => 'Guinea-Bissau', 'code' => 'GNB'],
        93  => ['id' => 93, 'name' => 'Guyana', 'code' => 'GUY'],
        94  => ['id' => 94, 'name' => 'Haiti', 'code' => 'HTI'],
        95  => ['id' => 95, 'name' => 'Holy See', 'code' => 'VAT'],
        96  => ['id' => 96, 'name' => 'Honduras', 'code' => 'HND'],
        97  => ['id' => 97, 'name' => 'Hong Kong', 'code' => 'HKG'],
        98  => ['id' => 98, 'name' => 'Hungary', 'code' => 'HUN'],
        99  => ['id' => 99, 'name' => 'Iceland', 'code' => 'ISL'],
        100 => ['id' => 100, 'name' => 'India', 'code' => 'IND'],
        101 => ['id' => 101, 'name' => 'Indonesia', 'code' => 'IDN'],
        102 => ['id' => 102, 'name' => 'Iran', 'code' => 'IRN'],
        103 => ['id' => 103, 'name' => 'Iraq', 'code' => 'IRQ'],
        104 => ['id' => 104, 'name' => 'Ireland', 'code' => 'IRL'],
        105 => ['id' => 105, 'name' => 'Isle of Man', 'code' => 'IMN'],
        106 => ['id' => 106, 'name' => 'Israel', 'code' => 'ISR'],
        107 => ['id' => 107, 'name' => 'Italy', 'code' => 'ITA'],
        108 => ['id' => 108, 'name' => 'Ivory Coast', 'code' => 'CIV'],
        109 => ['id' => 109, 'name' => 'Jamaica', 'code' => 'JAM'],
        110 => ['id' => 110, 'name' => 'Japan', 'code' => 'JPN'],
        111 => ['id' => 111, 'name' => 'Jersey', 'code' => 'JEY'],
        112 => ['id' => 112, 'name' => 'Jordan', 'code' => 'JOR'],
        113 => ['id' => 113, 'name' => 'Kazakhstan', 'code' => 'KAZ'],
        114 => ['id' => 114, 'name' => 'Kenya', 'code' => 'KEN'],
        115 => ['id' => 115, 'name' => 'Kiribati', 'code' => 'KIR'],
        116 => ['id' => 116, 'name' => 'Kuwait', 'code' => 'KWT'],
        117 => ['id' => 117, 'name' => 'Kyrgyzstan', 'code' => 'KGZ'],
        118 => ['id' => 118, 'name' => 'Laos', 'code' => 'LAO'],
        119 => ['id' => 119, 'name' => 'Latvia', 'code' => 'LVA'],
        120 => ['id' => 120, 'name' => 'Lebanon', 'code' => 'LBN'],
        121 => ['id' => 121, 'name' => 'Lesotho', 'code' => 'LSO'],
        122 => ['id' => 122, 'name' => 'Liberia', 'code' => 'LBR'],
        123 => ['id' => 123, 'name' => 'Libya', 'code' => 'LBY'],
        124 => ['id' => 124, 'name' => 'Liechtenstein', 'code' => 'LIE'],
        125 => ['id' => 125, 'name' => 'Lithuania', 'code' => 'LTU'],
        126 => ['id' => 126, 'name' => 'Luxembourg', 'code' => 'LUX'],
        127 => ['id' => 127, 'name' => 'Macau', 'code' => 'MAC'],
        128 => ['id' => 128, 'name' => 'Macedonia', 'code' => 'MKD'],
        129 => ['id' => 129, 'name' => 'Madagascar', 'code' => 'MDG'],
        130 => ['id' => 130, 'name' => 'Malawi', 'code' => 'MWI'],
        131 => ['id' => 131, 'name' => 'Malaysia', 'code' => 'MYS'],
        132 => ['id' => 132, 'name' => 'Maldives', 'code' => 'MDV'],
        133 => ['id' => 133, 'name' => 'Mali', 'code' => 'MLI'],
        134 => ['id' => 134, 'name' => 'Malta', 'code' => 'MLT'],
        135 => ['id' => 135, 'name' => 'Marshall Islands', 'code' => 'MHL'],
        136 => ['id' => 136, 'name' => 'Martinique', 'code' => 'MTQ'],
        137 => ['id' => 137, 'name' => 'Mauritania', 'code' => 'MRT'],
        138 => ['id' => 138, 'name' => 'Mauritius', 'code' => 'MUS'],
        139 => ['id' => 139, 'name' => 'Mayotte', 'code' => 'MYT'],
        140 => ['id' => 140, 'name' => 'Mexico', 'code' => 'MEX'],
        141 => ['id' => 141, 'name' => 'Micronesia', 'code' => 'FSM'],
        142 => ['id' => 142, 'name' => 'Moldova', 'code' => 'MDA'],
        143 => ['id' => 143, 'name' => 'Monaco', 'code' => 'MCO'],
        144 => ['id' => 144, 'name' => 'Mongolia', 'code' => 'MNG'],
        145 => ['id' => 145, 'name' => 'Montenegro', 'code' => 'MNE'],
        146 => ['id' => 146, 'name' => 'Montserrat', 'code' => 'MSR'],
        147 => ['id' => 147, 'name' => 'Morocco', 'code' => 'MAR'],
        148 => ['id' => 148, 'name' => 'Mozambique', 'code' => 'MOZ'],
        149 => ['id' => 149, 'name' => 'Myanmar', 'code' => 'MMR'],
        150 => ['id' => 150, 'name' => 'Namibia', 'code' => 'NAM'],
        151 => ['id' => 151, 'name' => 'Nauru', 'code' => 'NRU'],
        152 => ['id' => 152, 'name' => 'Nepal', 'code' => 'NPL'],
        153 => ['id' => 153, 'name' => 'Netherlands Antilles', 'code' => 'ANT'],
        154 => ['id' => 154, 'name' => 'Netherlands', 'code' => 'NLD'],
        155 => ['id' => 155, 'name' => 'New Caledonia', 'code' => 'NCL'],
        156 => ['id' => 156, 'name' => 'New Zealand', 'code' => 'NZL'],
        157 => ['id' => 157, 'name' => 'Nicaragua', 'code' => 'NIC'],
        158 => ['id' => 158, 'name' => 'Niger', 'code' => 'NER'],
        159 => ['id' => 159, 'name' => 'Nigeria', 'code' => 'NGA'],
        160 => ['id' => 160, 'name' => 'Niue', 'code' => 'NIU'],
        161 => ['id' => 161, 'name' => 'Norfolk Island', 'code' => 'NFK'],
        162 => ['id' => 162, 'name' => 'North Korea', 'code' => 'PRK'],
        163 => ['id' => 163, 'name' => 'Northern Mariana Islands', 'code' => 'MNP'],
        164 => ['id' => 164, 'name' => 'Norway', 'code' => 'NOR'],
        165 => ['id' => 165, 'name' => 'Oman', 'code' => 'OMN'],
        166 => ['id' => 166, 'name' => 'Pakistan', 'code' => 'PAK'],
        167 => ['id' => 167, 'name' => 'Palau', 'code' => 'PLW'],
        168 => ['id' => 168, 'name' => 'Palestinian Territories', 'code' => 'PSE'],
        169 => ['id' => 169, 'name' => 'Panama', 'code' => 'PAN'],
        170 => ['id' => 170, 'name' => 'Papua New Guinea', 'code' => 'PNG'],
        171 => ['id' => 171, 'name' => 'Paraguay', 'code' => 'PRY'],
        172 => ['id' => 172, 'name' => 'Peru', 'code' => 'PER'],
        173 => ['id' => 173, 'name' => 'Philippines', 'code' => 'PHL'],
        174 => ['id' => 174, 'name' => 'Pitcairn Islands', 'code' => 'PCN'],
        175 => ['id' => 175, 'name' => 'Poland', 'code' => 'POL'],
        176 => ['id' => 176, 'name' => 'Portugal', 'code' => 'PRT'],
        177 => ['id' => 177, 'name' => 'Puerto Rico', 'code' => 'PRI'],
        178 => ['id' => 178, 'name' => 'Qatar', 'code' => 'QAT'],
        179 => ['id' => 179, 'name' => 'Romania', 'code' => 'ROU'],
        180 => ['id' => 180, 'name' => 'Russia', 'code' => 'RUS'],
        181 => ['id' => 181, 'name' => 'Rwanda', 'code' => 'RWA'],
        182 => ['id' => 182, 'name' => 'RÃ©union', 'code' => 'REU'],
        183 => ['id' => 183, 'name' => 'Saba', 'code' => 'BES'],
        184 => ['id' => 184, 'name' => 'Saint BarthÃ©lemy', 'code' => 'BLM'],
        185 => ['id' => 185, 'name' => 'Saint Christopher & Nevis', 'code' => 'KNA'],
        186 => ['id' => 186, 'name' => 'Saint Helena', 'code' => 'SHN'],
        187 => ['id' => 187, 'name' => 'Saint Lucia', 'code' => 'LCA'],
        188 => ['id' => 188, 'name' => 'Saint Martin', 'code' => 'MAF'],
        189 => ['id' => 189, 'name' => 'Saint Pierre & Miquelon', 'code' => 'SPM'],
        190 => ['id' => 190, 'name' => 'Saint Vincent & The Grenadines', 'code' => 'VCT'],
        191 => ['id' => 191, 'name' => 'Samoa', 'code' => 'WSM'],
        192 => ['id' => 192, 'name' => 'San Marino', 'code' => 'SMR'],
        193 => ['id' => 193, 'name' => 'Sao Tome & Principe', 'code' => 'STP'],
        194 => ['id' => 194, 'name' => 'Saudi Arabia', 'code' => 'SAU'],
        195 => ['id' => 195, 'name' => 'Senegal', 'code' => 'SEN'],
        196 => ['id' => 196, 'name' => 'Serbia', 'code' => 'SRB'],
        197 => ['id' => 197, 'name' => 'Seychelles', 'code' => 'SYC'],
        198 => ['id' => 198, 'name' => 'Sierra Leone', 'code' => 'SLE'],
        199 => ['id' => 199, 'name' => 'Singapore', 'code' => 'SGP'],
        200 => ['id' => 200, 'name' => 'Sint Eustatius', 'code' => 'BES'],
        201 => ['id' => 201, 'name' => 'Sint Maarten', 'code' => 'SXM'],
        202 => ['id' => 202, 'name' => 'Slovakia', 'code' => 'SVK'],
        203 => ['id' => 203, 'name' => 'Slovenia', 'code' => 'SVN'],
        204 => ['id' => 204, 'name' => 'Solomon Islands', 'code' => 'SLB'],
        205 => ['id' => 205, 'name' => 'Somalia', 'code' => 'SOM'],
        206 => ['id' => 206, 'name' => 'Somaliland', 'code' => 'SOM'],
        207 => ['id' => 207, 'name' => 'South Africa', 'code' => 'ZAF'],
        208 => ['id' => 208, 'name' => 'South Georgia & The South Sandwish Islands', 'code' => 'SGS'],
        209 => ['id' => 209, 'name' => 'South Korea', 'code' => 'KOR'],
        210 => ['id' => 210, 'name' => 'South Sudan', 'code' => 'SSD'],
        211 => ['id' => 211, 'name' => 'Spain', 'code' => 'ESP'],
        212 => ['id' => 212, 'name' => 'Sri Lanka', 'code' => 'LKA'],
        213 => ['id' => 213, 'name' => 'Sudan', 'code' => 'SDN'],
        214 => ['id' => 214, 'name' => 'Suriname', 'code' => 'SUR'],
        215 => ['id' => 215, 'name' => 'Swaziland', 'code' => 'SWZ'],
        216 => ['id' => 216, 'name' => 'Sweden', 'code' => 'SWE'],
        217 => ['id' => 217, 'name' => 'Switzerland', 'code' => 'CHE'],
        218 => ['id' => 218, 'name' => 'Syria', 'code' => 'SYR'],
        219 => ['id' => 219, 'name' => 'Taiwan', 'code' => 'TWN'],
        220 => ['id' => 220, 'name' => 'Tajikistan', 'code' => 'TJK'],
        221 => ['id' => 221, 'name' => 'Tanzania', 'code' => 'TZA'],
        222 => ['id' => 222, 'name' => 'Thailand', 'code' => 'THA'],
        223 => ['id' => 223, 'name' => 'Togo', 'code' => 'TGO'],
        224 => ['id' => 224, 'name' => 'Tokelau', 'code' => 'TKL'],
        225 => ['id' => 225, 'name' => 'Tonga', 'code' => 'TON'],
        226 => ['id' => 226, 'name' => 'Trinidad & Tobago', 'code' => 'TTO'],
        227 => ['id' => 227, 'name' => 'Tunisia', 'code' => 'TUN'],
        228 => ['id' => 228, 'name' => 'Turkey', 'code' => 'TUR'],
        229 => ['id' => 229, 'name' => 'Turkmenistan', 'code' => 'TKM'],
        230 => ['id' => 230, 'name' => 'Turks & Caicos Islands', 'code' => 'TCA'],
        231 => ['id' => 231, 'name' => 'Tuvalu', 'code' => 'TUV'],
        232 => ['id' => 232, 'name' => 'Uganda', 'code' => 'UGA'],
        233 => ['id' => 233, 'name' => 'Ukraine', 'code' => 'UKR'],
        234 => ['id' => 234, 'name' => 'United Arab Emirates', 'code' => 'ARE'],
        235 => ['id' => 235, 'name' => 'United Kingdom', 'code' => 'GBR'],
        236 => ['id' => 236, 'name' => 'United States', 'code' => 'USA'],
        237 => ['id' => 237, 'name' => 'United States Virgin Islands', 'code' => 'VIR'],
        238 => ['id' => 238, 'name' => 'Uruguay', 'code' => 'URY'],
        239 => ['id' => 239, 'name' => 'Uzbekistan', 'code' => 'UZB'],
        240 => ['id' => 240, 'name' => 'Vanuatu', 'code' => 'VUT'],
        241 => ['id' => 241, 'name' => 'Venezuela', 'code' => 'VEN'],
        242 => ['id' => 242, 'name' => 'Vietnam', 'code' => 'VNM'],
        243 => ['id' => 243, 'name' => 'Wallis & Futuna', 'code' => 'WLF'],
        244 => ['id' => 244, 'name' => 'Western Sahara', 'code' => 'ESH'],
        245 => ['id' => 245, 'name' => 'Yemen', 'code' => 'YEM'],
        246 => ['id' => 246, 'name' => 'Zambia', 'code' => 'ZMB'],
        247 => ['id' => 247, 'name' => 'Zimbabwe', 'code' => 'ZWE']
    ],
    'language' => [
        'EN' => 'English',
        'FR' => 'French',
    ],
    'resource' => [
        'Aluminium '            => 'Aluminium',
        'Base metals'           => 'Base metals',
        'Bauxite'               => 'Bauxit',
        'Coal'                  => 'Coal',
        'Cobalt'                => 'Cobal',
        'Copper'                => 'Copper',
        'Crude oil'             => 'Crud',
        'Diamonds'              => 'Diamonds',
        'Gas'                   => 'Ga',
        'Gold'                  => 'Gold',
        'Iron ore '             => 'Iron ore ',
        'Lapis lazuli'          => 'Lapis lazuli',
        'Lead'                  => 'Lead',
        'Lithium'               => 'Lithium',
        'Manganese'             => 'Manganese',
        'Molybdenum'            => 'Molybdenum',
        'Nickel'                => 'Nickel',
        'Phosphate rock'        => 'Phosphate rock',
        'Platinum Group Metals' => 'Platinum Group Metals',
        'Precious stones'       => 'Precious stones',
        'Quartz'                => 'Quartz',
        'Semi-precious stones'  => 'Semi-precious stones',
        'Silver'                => 'Silver',
        'Titanium'              => 'Titanium',
        'Uranium'               => 'Uranium',
        'Zinc'                  => 'Zinc',
        'Citrus'                => 'Citrus',
        'Food crops'            => 'Food crops',
        'Hydrocarbons'          => 'Hydrocarbons',
        'Palm oil'              => 'Palm oil',
        'Rubber'                => 'Rubber',
        'Soy'                   => 'Soy',
        'Sugar'                 => 'Sugar',
        'Timber'                => 'Timber'
    ],
    'pdf_structure'     => ['structured','scanned'],
    'pdf_process_path'  => env('PDF_PROCESSOR_PATH'),
    'annotation_tags'   => ["Country",
                            "Local-Company-Name",
                            "Legal-Enterprise-Identifier",
                            "Corporate-headquarters",
                            "Company-structure",
                            "Parent-companies-or-affilates",
                            "Company-website",
                            "Type-of-document",
                            "Project-title",
                            "Name/number-of-field-block-or-deposit",
                            "Location-longitude-and-latitude",
                            "Closest-community",
                            "Date-of-issue-of-title/permit",
                            "Date-of-ratification",
                            "Stabilization-clause",
                            "Arbitration-and-dispute-resolution"]
                            ];